-- TABELA PAGAMENTO
CREATE TABLE TB_Pagamento (
    ID_Pagamento INTEGER GENERATED ALWAYS AS IDENTITY,
    ID_Inscricao INTEGER,
    DH_DataPagamento TIMESTAMP,
    VL_ValorPago DECIMAL,
    TP_MetodoPagamento VARCHAR,
    CD_Transacao VARCHAR
);
-- PRIMARY KEY
ALTER TABLE TB_Pagamento ADD CONSTRAINT PK_Pagamento PRIMARY KEY (ID_Pagamento);

-- TABELA CERTIFICADO
CREATE TABLE TB_Certificado (
    ID_Certificado INTEGER GENERATED ALWAYS AS IDENTITY,
    ID_Inscricao INTEGER,
    CD_Validacao VARCHAR,
    DH_Emissao TIMESTAMP
);
-- PRIMARY KEY
ALTER TABLE TB_Certificado ADD CONSTRAINT PK_Certificado PRIMARY KEY (ID_Certificado);

-- TABELA USUARIO
CREATE TABLE TB_Usuario (
    ID_Usuario INTEGER GENERATED ALWAYS AS IDENTITY,
    CD_CPF VARCHAR,
    DS_Email VARCHAR,
    DS_Nome VARCHAR,
    DS_Instituicao VARCHAR,
    DS_Escolaridade VARCHAR
);
-- PRIMARY KEY
ALTER TABLE TB_Usuario ADD CONSTRAINT PK_Usuario PRIMARY KEY (ID_Usuario);

-- TABELA REGISTRO
CREATE TABLE TB_Registro (
    ID_Registro INTEGER GENERATED ALWAYS AS IDENTITY,
    ID_EventoPai INTEGER,
    TP_Registro VARCHAR,
    DS_Titulo VARCHAR,
    DS_Descricao VARCHAR,
    DS_Local VARCHAR,
    DH_Inicio TIMESTAMP,
    DH_Fim TIMESTAMP,
    TP_Area VARCHAR,
    ST_Submissao VARCHAR
);
-- PRIMARY KEY
ALTER TABLE TB_Registro ADD CONSTRAINT PK_Registro PRIMARY KEY (ID_Registro);

-- TABELA INSCRICAO
CREATE TABLE TB_Inscricao (
    ID_Inscricao INTEGER GENERATED ALWAYS AS IDENTITY,
    ID_Registro INTEGER,
    ID_Usuario INTEGER,
    DH_DataInscricao TIMESTAMP,
    TP_Inscricao VARCHAR,
    ST_Pagamento VARCHAR,
    VL_CustoInscricao DECIMAL,
    ST_Presente BOOLEAN
);
-- PRIMARY KEY
ALTER TABLE TB_Inscricao ADD CONSTRAINT PK_Inscricao PRIMARY KEY (ID_Inscricao);

-- DEFINIÇÃO DAS CONSTRAINTS
-- FOREIGN KEY PAGAMENTO/INSCRICAO
ALTER TABLE TB_Pagamento ADD CONSTRAINT FK_Pagamento_Inscricao
    FOREIGN KEY (ID_Inscricao)
    REFERENCES TB_Inscricao (ID_Inscricao);

-- FOREIGN KEY CERTIFICADO/INSCRICAO
ALTER TABLE TB_Certificado ADD CONSTRAINT FK_Certificado_Inscricao
    FOREIGN KEY (ID_Inscricao)
    REFERENCES TB_Inscricao (ID_Inscricao);

-- UNIQUE KEY USUARIO/CPF
ALTER TABLE TB_Usuario ADD CONSTRAINT UK_Usuario_CPF UNIQUE (CD_CPF);
-- UNIQUE KEY USUARIO/EMAIL
ALTER TABLE TB_Usuario ADD CONSTRAINT UK_Usuario_Email UNIQUE (DS_Email);

-- FOREIGN KEY ATIVIDADE/EVENTO
ALTER TABLE TB_Registro ADD CONSTRAINT FK_Registro_EventoPai
    FOREIGN KEY (ID_EventoPai)
    REFERENCES TB_Registro (ID_Registro);

-- UNIQUE KEY INSCRICAO (USUARIO,REGISTRO)
ALTER TABLE TB_Inscricao ADD CONSTRAINT UK_Usuario_Registro UNIQUE (ID_Registro, ID_Usuario);
-- FOREIGN KEY INSCRICAO_USUARIO
ALTER TABLE TB_Inscricao ADD CONSTRAINT FK_Inscricao_Usuario
    FOREIGN KEY (ID_Usuario)
    REFERENCES TB_Usuario (ID_Usuario);
-- FOREIGN KEY INSCRICAO_REGISTRO
ALTER TABLE TB_Inscricao ADD CONSTRAINT FK_Inscricao_Registro
    FOREIGN KEY (ID_Registro)
    REFERENCES TB_Registro (ID_Registro);